### ISSUE TITLE
Not working under Centos 8

### ISSUE THREAD

**Issue by Elfearo** [kadirsert/nagios-plugins-check_linux_cpu#1]
Hey there. 

Really nice script, i used it to monitor a Centos 7 Server and it worked great. After updating to Centos it unfortunately doesnt work anymore. 

Output is: 

File "/usr/lib64/nagios/plugins/./check_linux_cpu.py", line 20
print "CPU Usage is CRITICAL: " + str(cpu_usage) + "% 
                                  ^
SyntaxError: invalid syntax

Maybe you could have a look.

Thank you very much

**Comment by kadirsert** [comment]
Hi,
Since CentOS version 8, Python interpreter does not come preinstalled. So one can install the version of Python that suits needs. The **_SyntaxError_** indicates that you are probably using python3.

Python3 support added to the plugin now. You should also change nagios command specifying the Python interpreter path:  `/usr/bin/python3 check_linux_cpu.py -w 80 -c 90`
